MyCRM/MyCRM/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from crm.views import sales

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 登录
    url(r'^login/', sales.login),
    # 注销
    url(r'^logout/', sales.logout, name='logout'),
    # 注册
    url(r'^reg/', sales.reg),

    url(r'^crm/', include('crm.urls')),


]

MyCRM/crm/urls.py
from django.conf.urls import url
from crm.views import sales, teacher

urlpatterns = [

    ### 销售相关 ###
    # 公有客户列表
    url(r'^customer_list/', sales.CustomerList.as_view(), name='customer'),
    # 私有客户
    url(r'^my_customer_list/', sales.CustomerList.as_view(), name='my_customer'),
    # 添加客户
    url(r'^customer/add/', sales.customer_add_or_edit, name='customer_add'),
    # 编辑客户
    url(r'^customer/edit/(\d+)/', sales.customer_add_or_edit, name='customer_edit'),

    # 全部咨询记录
    url(r'^consult_record_list/(\d+)/', sales.ConsultRecordList.as_view(), name='consult'),
    # 添加咨询记录
    url(r'^consult_record/add/', sales.consult_record_add_or_edit, name='consult_record_add'),
    # 编辑咨询记录
    url(r'^consult_record/edit/(\d+)/', sales.consult_record_add_or_edit, name='consult_record_edit'),

    # 全部报名记录
    url(r'^enrollment_list/(\d+)/', sales.EnrollmentList.as_view(), name='enrollment'),
    # 添加报名记录
    url(r'^enrollment/add/(?P<customer_id>\d+)/', sales.enrollment_add_or_edit, name='enrollment_add'),
    # 编辑报名记录
    url(r'^enrollment/edit/(?P<edit_id>\d+)/', sales.enrollment_add_or_edit, name='enrollment_edit'),


    ### 教师相关 ###
    # 班级列表
    url(r'^class_list/', teacher.ClassList.as_view(), name='class'),
    # 我的班级
    url(r'^my_class_list/', teacher.ClassList.as_view(), name='my_class'),
    # 添加班级
    url(r'^class/add/', teacher.class_add_or_edit, name='class_add'),
    # 编辑班级
    url(r'^class/edit/(\d+)/', teacher.class_add_or_edit, name='class_edit'),

    # 课程列表
    url(r'^course_list/(\d+)/', teacher.CourseList.as_view(), name='course'),
    # 添加课程
    url(r'^course/add/(?P<class_id>\d+)/', teacher.course_add_or_edit, name='course_add'),
    # # 编辑课程
    url(r'^course/edit/(?P<edit_id>\d+)/', teacher.course_add_or_edit, name='course_edit'),

    # 学习记录
    url(r'^study_record_list/(\d+)/', teacher.study_record_list, name='study_record'),

]

MyCRM/crm/models.py
from django.db import models
from django.contrib import auth
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, User
from django.utils.translation import ugettext_lazy as _
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe

# 咨询课程
course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

# 班级类型
class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

# 客户来源
source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

# 客户状态
enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
# 缴费记录
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


# 客户表
class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    network_consult_note = models.TextField(blank=True, null=True, verbose_name='网络咨询师咨询内容')
    date = models.DateTimeField("咨询日期", auto_now_add=True)
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    network_consultant = models.ForeignKey('UserProfile', blank=True, null=True, verbose_name='咨询师',
                                           related_name='network_consultant')
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True, )
    class_list = models.ManyToManyField('ClassList', verbose_name="意向班级", blank=True)

    # 根据已选择的意向班级格式化显示
    def show_classes(self):
        return ' | '.join([str(i) for i in self.class_list.all()])

    # 根据客户的状态显示不同的颜色
    def show_status(self):
        """
        ('signed', "已报名"),
        ('unregistered', "未报名"),
        ('studying', '学习中'),
        ('paid_in_full', "学费已交齐")
        """
        color_dit = {
            'signed': "green",
            'unregistered': "red",
            'studying': 'deepskyblue',
            'paid_in_full': "midnightblue"
        }
        return mark_safe('<span style="color: {}">{}</span>'.format(color_dit[self.status], self.get_status_display()))

    # 根据报名状态显示不同的报名记录标签
    def enroll_link(self):
        # 如果有报名记录
        if self.enrollment_set.exists():
            return '1'
        else:
            return '0'


    class Meta:
        verbose_name = '客户列表'
        verbose_name_plural = '客户列表'

    def __str__(self):
        return '{}<{}>'.format(self.name, self.qq)



# 校区表
class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    class Meta:
        verbose_name = '校区列表'
        verbose_name_plural = '校区列表'

    def __str__(self):
        return self.name


# 合同表
class ContractTemplate(models.Model):
    """
    合同模板表
    """
    name = models.CharField("合同名称", max_length=128, unique=True)
    content = models.TextField("合同内容")
    date = models.DateField(auto_now=True)


# 班级表
class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区")
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')
        verbose_name = '班级列表'
        verbose_name_plural = '班级列表'

    def __str__(self):
        return '{}{}({})'.format(self.get_course_display(), self.semester, self.campuses)

    def show_teacher(self):
        return ' | '.join([str(i) for i in self.teachers.all()])


# 咨询(跟进)记录表
class ConsultRecord(models.Model):
    """
    咨询记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
    note = models.TextField(verbose_name="咨询内容...")
    status = models.CharField("咨询状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="咨询记录人", related_name='records')
    date = models.DateTimeField("咨询日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


# 报名表
class Enrollment(models.Model):
    """
    报名表
    """
    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campuses', verbose_name='校区')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')


# 缴费记录表
class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True)
    customer = models.ForeignKey('Customer', verbose_name="客户")
    consultant = models.ForeignKey('UserProfile', verbose_name="销售")
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True)


# 课程记录表
class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="是否有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)

MyCRM/crm/forms.py
from django import forms
from django.core.exceptions import ValidationError

from crm import models


class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            # 给每个字段的标签都加上样式
            field.widget.attrs.update({'class': 'form-control'})


# 注册form
class RegForm(BaseForm):
    username = forms.CharField(
        label='用户名',
        widget=forms.widgets.EmailInput(),
        max_length=12,
        error_messages={
            'required': '不能为空',
        }
    )
    password = forms.CharField(
        label='密码',
        widget=forms.widgets.PasswordInput(),
        min_length=6,
        max_length=24,
        error_messages={
            'min_length': '最小长度为6',
            'required': '不能为空'
        }
    )
    re_password = forms.CharField(
        label='确认密码',
        widget=forms.widgets.PasswordInput(),
        min_length=6,
        max_length=24,
        error_messages={
            'min_length': '最小长度为6',
            'required': '不能为空'
        }
    )
    name = forms.CharField(
        label='姓名',
        widget=forms.widgets.Input(),
        min_length=1,
        max_length=12,
        error_messages={
            'min_length': '最小长度为1',
            'required': '不能为空'
        }
    )

    # 配置所有字段, 如果自己重写了某个字段, 则配置不生效
    class Meta:
        model = models.UserProfile
        # fields = '__all__'    # 所有字段
        fields = ['username', 'password', 're_password', 'name', 'department']
        # exclude = []    # 要排除的字段
        # 给字段设置类型
        widgets = {
            # 'password': forms.widgets.PasswordInput(attrs={'class': 'form-control'})  # 给这个字段单独设置样式
            'password': forms.widgets.PasswordInput()
        }
        # 给字段设置label
        labels = {
            'department': '部门',
        }

    # 全局钩子
    def clean(self):
        pwd = self.cleaned_data.get('password')
        re_pwd = self.cleaned_data.get('re_password')
        if re_pwd == pwd:
            return self.cleaned_data

        self.add_error('re_password', '两次密码不一致')
        raise ValidationError('两次密码不一致')


# 添加客户form
class CustomerForm(BaseForm):
    class Meta:
        model = models.Customer
        fields = '__all__'

        widgets = {
            'course': forms.widgets.SelectMultiple,
        }


# 添加咨询记录form
class ConsultRecordForm(BaseForm):
    class Meta:
        model = models.ConsultRecord
        exclude = ['delete_status']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 获取当前用户的私有客户
        customer_choice = [(i.id, i) for i in self.instance.consultant.customers.all()]
        customer_choice.insert(0, ('', '---------'))

        # 所咨询客户只能是当前用户的私有客户
        self.fields['customer'].widget.choices = customer_choice
        # 限制咨询记录人为当前用户
        self.fields['consultant'].widget.choices =  [(self.instance.consultant.id, self.instance.consultant),]


# 报名记录form
class EnrollmentForm(BaseForm):
    class Meta:
        model = models.Enrollment
        exclude = ['contract_approved', 'delete_status']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 限制客户只能是当前要报名的客户
        self.fields['customer'].widget.choices = [(self.instance.customer_id, self.instance.customer)]
        # 限制班级只能是意向班级
        self.fields['enrolment_class'].widget.choices = [(i.id, i) for i in self.instance.customer.class_list.all()]


# 班级form
class ClassForm(BaseForm):
    class Meta:
        model = models.ClassList
        fields = '__all__'


# 课程form
class CourseForm(BaseForm):
    class Meta:
        model = models.CourseRecord
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 所选择的班级只能是当前要添加的班级
        self.fields['re_class'].widget.choices = [(self.instance.re_class_id, self.instance.re_class),]
        # 限制讲师为当前用户
        self.fields['teacher'].widget.choices =  [(self.instance.teacher.id, self.instance.teacher),]

# 课程记录form
class StudyRecordForm(BaseForm):
    class Meta:
        model = models.StudyRecord
        fields = '__all__'

MyCRM/templates/crm/sales/consult_record_add_or_edit.html
{% extends 'base.html' %}
{% load static %}

{% block username %}
    {{ user.name }}
{% endblock %}

{% block content %}
    <div class="panel panel-info">
        <h3 class="text-center">
            {% if edit_id %}
                编辑咨询记录
            {% else %}
                添加咨询记录
            {% endif %}
        </h3>
        <div class="panel-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-md-offset-2">
                        <form class="form-horizontal" novalidate action="" method="post">
                            {% csrf_token %}
                            {% for field in form_obj %}
                                <div class="form-group row {% if field.errors %}has-error{% endif %}">
                                    <label class="col-md-3 control-label"
                                           for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    <div class="col-md-8">
                                        {{ field }}
                                    </div>
                                    <span style="color: red">{{ field.errors.0 }}</span>
                                </div>
                            {% endfor %}
                            <!-- 提交 -->
                            <div class="form-group">
                                <div class="text-center">
                                    <a href="{% url 'consult' '0' %}" class="btn btn-warning">取消</a>
                                    <button type="submit" class="btn btn-success">提交</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
    <script>
        $('input, select').focus(function () {
            $(this).parent().next().text('').parent().removeClass('has-error')
        })
    </script>
{% endblock %}

MyCRM/templates/crm/sales/consult_record_list.html
{% extends 'base.html' %}

{% block css %}
    <style>
        th, tr {
            text-align: center;
        }
    </style>
{% endblock %}

{% block username %}
    {{ user.name }}
{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading" style="font-size: 20px;"><b>咨询记录</b></div>
        <hr>
        <div class="panel-body">
            <div>
                <div class="float-right">
                    <a href="{% url 'consult_record_add' %}" class="btn btn-danger btn-sm" style="margin-left: 24px">添加记录</a>
                </div>
            </div>
            <form action="" method="post">
                {% csrf_token %}
                <div class="btn-group invisible" id="se">
                    <select class="form-control" name="action">
                        <option selected>---选择操作---</option>
                        <option value="delete">删除</option>
                    </select>
                    <button class="btn btn-success" type="submit">ok</button>
                </div>
                <table class="table table-hover table-striped">
                    <thead>
                    <tr>
                        <th>选择</th>
                        <th>#</th>
                        <th>客户</th>
                        <th>咨询内容</th>
                        <th>咨询状态</th>
                        <th>咨询日期</th>
                        <th>咨询记录人</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for record in all_consult_record %}
                        <tr>
                            <td><input type="checkbox" value="{{ record.id }}" name="id"></td>
                            <td>{{ forloop.counter }}</td>
                            <td>
                                <a href="/crm/consult_record/edit/{{ record.id }}/">{{ record.customer }}</a>
                            </td>
                            <td>{{ record.note|truncatechars:7 }}</td>
                            <td>{{ record.get_status_display }}</td>
                            <td>{{ record.date }}</td>
                            <td>{{ record.consultant }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </form>
        </div>

        <!-- 页码 -->
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {{ all_tag }}
            </ul>
        </nav>

    </div>

{% endblock %}

{% block js %}
    <script>
        $('input:checkbox').click(function () {
            {#判断是否至少选中一个复选框#}
            if ($("input:checkbox[name='id']:checked").length > 0) {
                $('#se').removeClass('invisible')
            } else {
                $('#se').addClass('invisible')
            }
        })
    </script>
{% endblock %}

MyCRM/templates/crm/sales/customer_add_or_edit.html
{% extends 'base.html' %}
{% load static %}

{% block username %}
    {{ user.name }}
{% endblock %}

{% block content %}
    <div class="panel panel-info">
        <h3 class="text-center">
            {% if edit_id %}
                编辑客户
            {% else %}
                添加客户
            {% endif %}
        </h3>
        <div class="panel-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-md-offset-2">
                        <form class="form-horizontal" novalidate action="" method="post">
                            {% csrf_token %}
                            {% for field in form_obj %}
                                <div class="form-group row {% if field.errors %}has-error{% endif %}">
                                    <label class="col-md-3 control-label"
                                           for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    <div class="col-md-8">
                                        {{ field }}
                                    </div>
                                    <span style="color: red">{{ field.errors.0 }}</span>
                                </div>
                            {% endfor %}
                            <!-- 提交 -->
                            <div class="form-group">
                                <div class="text-center">
                                    <a href="{% url 'customer' %}" class="btn btn-warning">取消</a>
                                    <button type="submit" class="btn btn-success">提交</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
    <script>
        $('input, select').focus(function () {
            $(this).parent().next().text('').parent().removeClass('has-error')
        })
    </script>
{% endblock %}

MyCRM/templates/crm/sales/customer_list.html
{% extends 'base.html' %}

{% block css %}
    <style>
        th, tr {
            text-align: center;
        }
    </style>
{% endblock %}

{% block username %}
    {{ user.name }}
{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading" style="font-size: 20px;"><b>全部客户信息</b></div>
        <hr>
        <div class="panel-body">
            <div>
                <div class="float-right">
                    <form action="">
                        <div class="input-group">
                            <input type="text" class="form-control" name="query" placeholder="搜索...">
                            <span class="mdi mdi-magnify"></span>
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">搜索客户</button>
                            </div>
                            <a href="{% url 'customer_add' %}?{{ next }}" class="btn btn-danger btn-sm"
                               style="margin-left: 24px">添加客户</a>
                        </div>
                    </form>
                </div>
            </div>
            <form action="" method="post">
                {% csrf_token %}
                <div class="btn-group invisible" id="se">
                    <select class="form-control" name="action">
                        <option selected>---选择操作---</option>
                        <optgroup label="">
                            {% if request.path_info == "/crm/customer_list/" %}
                                <option value="private">设置私有</option>
                            {% else %}
                                <option value="public">设为公有</option>
                            {% endif %}
                        </optgroup>
                        <optgroup label="">
                            <option value="delete">删除</option>
                        </optgroup>
                    </select>
                    <button class="btn btn-success" type="submit">ok</button>
                </div>
                <table class="table table-hover table-striped">
                    <thead>
                    <tr>
                        <th>选择</th>
                        <th>#</th>
                        <th>QQ</th>
                        <th>姓名</th>
                        <th>性别</th>
                        <th>咨询课程</th>
                        <th>班级类型</th>
                        <th>状态</th>
                        <th>咨询日期</th>
                        <th>最后咨询日期</th>
                        <th>咨询记录</th>
                        <th>销售</th>
                        <th>意向班级</th>
                        {% if request.path_info == "/crm/my_customer_list/" %}
                            <th>报名记录</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for customer in all_customer %}
                        <tr>
                            <td><input type="checkbox" value="{{ customer.id }}" name="id"></td>
                            <td>{{ forloop.counter }}</td>
                            <td>
                                <a class="btn btn-outline-info btn-sm"
                                   href="/crm/customer/edit/{{ customer.id }}/?{{ next }}">{{ customer.qq }}</a>
                            </td>
                            <td>{{ customer.name|default:'暂无' }}</td>
                            <td>{{ customer.get_sex_display }}</td>
                            <td>{{ customer.course }}</td>
                            <td>{{ customer.get_class_type_display }}</td>
                            <td>
                                {{ customer.show_status }}
                            </td>
                            <td>{{ customer.date }}</td>
                            <td>{{ customer.last_consult_date }}</td>
                            <td><a class="btn btn-info btn-sm" href="{% url 'consult' customer.id %}">查看</a></td>
                            <td>{{ customer.consultant|default:'暂无' }}</td>
                            <td>{{ customer.show_classes }}</td>
                            {% if request.path_info == "/crm/my_customer_list/" %}
                                <th>
                                    {% if customer.enroll_link == '0' %}
                                        <a class="btn btn-success btn-sm"
                                           href='/crm/enrollment/add/{{ customer.id }}/?{{ next }}'>报名</a>
                                    {% else %}
                                        <a class="btn btn-info btn-sm" href='{% url 'enrollment' customer.id %}'>查看</a>
                                        <a class="btn btn-success btn-sm"
                                           href='/crm/enrollment/add/{{ customer.id }}/?{{ next }}'>报名</a>
                                    {% endif %}
                                </th>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </form>
        </div>

        <!-- 页码 -->
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {{ all_tag }}
            </ul>
        </nav>

    </div>

{% endblock %}

{% block js %}
    <script>
        $('input:checkbox').click(function () {
            {#判断是否至少选中一个复选框#}
            if ($("input:checkbox[name='id']:checked").length > 0) {
                $('#se').removeClass('invisible')
            } else {
                $('#se').addClass('invisible')
            }
        })
    </script>
{% endblock %}

MyCRM/templates/crm/sales/enrollment_add_or_edit.html
{% extends 'base.html' %}
{% load static %}

{% block username %}
    {{ user.name }}
{% endblock %}

{% block content %}
    <div class="panel panel-info">
        <h3 class="text-center">
            报名记录
        </h3>
        <div class="panel-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-md-offset-2">
                        <form class="form-horizontal" novalidate action="" method="post">
                            {% csrf_token %}
                            {% for field in form_obj %}
                                <div class="form-group row {% if field.errors %}has-error{% endif %}">
                                    <label class="col-md-3 control-label"
                                           for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    <div class="col-md-8">
                                        {{ field }}
                                    </div>
                                    <span style="color: red">{{ field.errors.0 }}</span>
                                </div>
                            {% endfor %}
                            <!-- 提交 -->
                            <div class="form-group">
                                <div class="text-center">
                                    <a href="{% if next %}{{ next }}{% else %}{% url 'enrollment' '0' %}{% endif %}" class="btn btn-warning">取消</a>
                                    <button type="submit" class="btn btn-success">提交</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
    <script>
        $('input, select').focus(function () {
            $(this).parent().next().text('').parent().removeClass('has-error')
        })
    </script>
{% endblock %}